# Generated by Django 3.2.5 on 2021-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
