# Generated by Django 3.2.5 on 2021-07-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15)),
                ('unit_price', models.IntegerField(max_length=10)),
                ('tax_percent', models.IntegerField(max_length=10)),
            ],
        ),
    ]
