# Generated by Django 3.2.5 on 2021-07-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_line',
            old_name='order_id',
            new_name='order',
        ),
    ]
