# Generated by Django 3.2.5 on 2021-07-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_order_id_order_line_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(null=True),
        ),
    ]
